// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgTo9WQxD_6X77vl--pfLMq3o_MGmXcwM',
    appId: '1:646966713278:web:b2b66c25ecf40e927cb7ef',
    messagingSenderId: '646966713278',
    projectId: 'c-linked',
    authDomain: 'c-linked.firebaseapp.com',
    storageBucket: 'c-linked.appspot.com',
    measurementId: 'G-44QFFL6W4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASEDadhDzD63UAyyPZmGiBdmcMfQDQ5_g',
    appId: '1:646966713278:android:2bf1a3d9a78b4cc07cb7ef',
    messagingSenderId: '646966713278',
    projectId: 'c-linked',
    storageBucket: 'c-linked.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnf3iIcq-h5ObCSLfClMXP3hveU4FRoxo',
    appId: '1:646966713278:ios:5de0e620ea5d558d7cb7ef',
    messagingSenderId: '646966713278',
    projectId: 'c-linked',
    storageBucket: 'c-linked.appspot.com',
    iosBundleId: 'com.example.cLinked',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnf3iIcq-h5ObCSLfClMXP3hveU4FRoxo',
    appId: '1:646966713278:ios:ab579bf11d8d4c3c7cb7ef',
    messagingSenderId: '646966713278',
    projectId: 'c-linked',
    storageBucket: 'c-linked.appspot.com',
    iosBundleId: 'com.example.cLinked.RunnerTests',
  );
}
